# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 08:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('team', models.CharField(max_length=255, verbose_name='Team')),
                ('slack_id', models.CharField(max_length=255, verbose_name='Slack ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='username')),
                ('real_name', models.CharField(blank=True, max_length=255, verbose_name='Real name')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Last name')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='Email')),
                ('commands_access', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Can execute commands')),
                ('timezone', models.CharField(blank=True, max_length=100, verbose_name='Timezone')),
                ('is_owner', models.BooleanField(default=False, verbose_name='Is owner')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Is admin')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddField(
            model_name='slackuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slack_users', to=settings.AUTH_USER_MODEL, verbose_name='Related user'),
        ),
        migrations.AlterUniqueTogether(
            name='slackuser',
            unique_together=set([('team', 'slack_id')]),
        ),
    ]
